### ISSUE TITLE
fix(image): use a higher resolution for the logo

### ISSUE THREAD

**Issue by PatrickMi** [maevsi/stomper#126]
The current logo in the maevsi invitation email has only a normal resolution so it looks a bit washed out on high res displays like the Mac Retina display or other high resolution screens

**Comment by dargmuesli** [comment]
I transferred this issue to the `stomper` repository :arrow_forward: 
Is it possible to add a screenshot showing the effect?

**Comment by PatrickMi** [comment]
Here are screenshots of the mail on a Mac and an iPhone. Once in the usual size and once a little zoomed in. We should think about using a svg image here
<img width="605" alt="Bildschirm­foto 2022-11-23 um 16 16 36" src="https://user-images.githubusercontent.com/25430449/203585758-f12245ae-88ae-4241-8a46-2d85d3e522a2.png">
<img width="920" alt="Bildschirm­foto 2022-11-23 um 16 16 57" src="https://user-images.githubusercontent.com/25430449/203585771-ad9dec24-12d0-4855-a256-47aa0f10c094.png">
![IMG_1508](https://user-images.githubusercontent.com/25430449/203585777-0c12bcaa-73a7-4656-b1af-02ef4d2ef9a3.jpeg)
![IMG_1509](https://user-images.githubusercontent.com/25430449/203585783-08ad091b-8638-49a2-89e2-84be670717ea.jpeg)

**Comment by dargmuesli** [comment]
Sadly (SVG) images in email are a bit problematic, especially in GMail: https://www.caniemail.com/features/image-svg/
To me it seems like GMail is the lowest common denominator for images in mails. Base issue for that is #104 already, even base64 images are not supported.
We should check which image types are supported by GMail to solve this issue.

It could even be the case that we have to drop support for some mail clients (GMail?) as it seems hard to support all at once :thinking:
