### ISSUE TITLE
fix: hotmail classifies emails as spam

### ISSUE THREAD

**Issue by PatrickMi** [maevsi/stomper#134]

**Comment by dargmuesli** [comment]
Any data like mail provider,...? We'd need to have the email forwarded to us so we can inspect it's headers to judge why it was classified as spam.

**Comment by dargmuesli** [comment]
To be more specific: we'd need the email exported, e.g. as `.eml`, to be able to look into the original headers. Could you send me the contact of the person who experienced that issue in a PN so I can ask them again?

**Comment by dargmuesli** [comment]
I have not received any further information on this topic until now. I checked with https://www.mail-tester.com and see no issues with our mail delivery. I'm going to close this issue for now and can reopen it once more information is available for sure!
