### ISSUE TITLE
fix(mjml): many clients render emails unreadable

### ISSUE THREAD

**Issue by dargmuesli** [maevsi/stomper#32]

**Comment by Bobomify** [comment]
![hotmail_outlook_web](https://user-images.githubusercontent.com/36385184/107868459-cd0f4300-6e84-11eb-9388-a8254bc89453.PNG)
hotmail_outlook_web

**Comment by dargmuesli** [comment]
Hopefully fixed by 6f1bc3b766859578f758dffd0a71f8cf9a7aada2.

**Comment by dargmuesli** [comment]
The fix will be on production soon, but I'll add a few more features to it first.
